spring:
    datasource:
        name: kftdb
        url: jdbc:oracle:thin:@172.16.5.81:1521:kftdb
        username: kftcl
        password: kftpasswd
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name:oracle.jdbc.driver.OracleDriver
########filters: stat
########maxActive: 20
########initialSize: 1
########maxWait: 60000
########minIdle: 1
########timeBetweenEvictionRunsMillis: 60000
########minEvictableIdleTimeMillis: 300000
########validationQuery: select 'x'
########testWhileIdle: true
########testOnBorrow: false
########testOnReturn: false
########poolPreparedStatements: true
########maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml