spring:
    datasource:
        name: kftdb
        url: jdbc:oracle:thin:@172.16.5.81:1521:kftdb
        username: kftcl
        password: kftpasswd
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name:oracle.jdbc.driver.OracleDriver
        # 下面为连接池的补充设置，应用到上面所有数据源中
mybatis:
  mapper-locations: classpath:sqlMap/*.xml